### ISSUE TITLE
llcp.h

### ISSUE THREAD

**Issue by pit001** [LieBtrau/arduino-ntag#1]
Hi - I get an error: 

ntagTest.ino:2:18: fatal error: llcp.h: No such file or directory

Btw: Is this libray to communicate by 
- I²C with the NT3H1101 or by 
- I²C with the PN532 (Elechouse ) reader and 'understand' the nTag structure from the chip at the other side ?

regards, pit

**Comment by LieBtrau** [comment]
Hi pit,
The llcp.h is not needed.  I cleaned up the include-directives in the example.  The readme file has also been updated.  There should no longer be confusion now about the use of the library: I²C with the NT3H1101.
Make sure you have installed the two additional libraries as mentioned in the readme.
