### ISSUE TITLE
Elusive bugs

### ISSUE THREAD

**Issue by benolayinka** [LieBtrau/arduino-ntag#10]
Thanks for your hard work with the library, there's not much available out there for these NXP ntags and I see you put a lot of hard work in to this!

I'm having a little bit of trouble with the library - it seems to erratically crash, failing to read or write tags. With a freshly erased tag, it usually works, but as soon as I write a message, I can't read it back. Running the examples causes my Arduino to loop, and sometimes to spit out garbage on the serial line.  I've stepped through a lot of the library with prints and sometimes normal function returns seem to crash the Arduino.

The only thing I can guess is that somehow, the Arduino is running out of program memory? I look with MemoryFree and it seems like I have plenty of memory before ntag.begin, but then the Arduino starts acting crazy so I can't see the results of later calls.

I don't see how this is possible, but could it be that somehow, during begin, more data gets read in to ram than is expected?

**Comment by benolayinka** [comment]
As an example, I'm running the following code now and getting various results.

`Ntag ntag(Ntag::NTAG_I2C_1K,2,5, 0x55);
  Serial.begin(9600);
  byte UID[7] = {0,0,0,0,0,0,0};
  ntag.getUid(UID, 7);
  Serial.println(UID[0], HEX);
  Serial.println(UID[1], HEX);
  Serial.println(UID[2], HEX);`

This is sometimes printing
4
51
7

And sometimes printing
0
0
0

And once or twice some other results. None of these are my UID.

**Comment by LieBtrau** [comment]
Hi Ben,
Can you upload your code somewhere on the internet and post a link here?  If I found some time, I can build it myself and see what goes wrong.
