### ISSUE TITLE
Get_Version command

### ISSUE THREAD

**Issue by Gerriko** [LieBtrau/arduino-ntag#12]
According to NXP documentation, "the GET_VERSION command is used to retrieve information about the NTAG family, the product version, storage size and other product data required to identify the specific
NTAG I2C plus."

How would I implement using your read/write/readblock/writeblock logic? I need to use 60h as the get version command.

**Comment by Gerriko** [comment]
I think I have misunderstood the NXP documentation. I got the GET_VERSION command to work using an NFC app on my phone, so I don't think this information can be read via I2C.

The info returned was 00:04:04:05:02:02:13:03

**Comment by LieBtrau** [comment]
I should check the datasheet, but I think that the GET_VERSION command is rather pointless from an I2C side of view.
As the Ntag is soldered on the PCB, the version of the ntag remains the same for ever.  You know what component is assembled on the PCB, so either hard code that info in your firmware or make it a parameter that you program to your units during production testing.
