### ISSUE TITLE
read function 

### ISSUE THREAD

**Issue by AA-IC-YPL** [LieBtrau/arduino-ntag#15]
Hi, I am testing my NXP NT3h2211 for my school project to see if it can run with your library. The only example went successful is clean. While running read or write just have no effect. I check there isn't write or read function in ntagadapter.cpp which present in the examples. Sorry I am new to all this stuff. If I asked a silly question please bear with me.

**Comment by LieBtrau** [comment]
The last time I tested it was using an STM32 BluePill, which has a lot more RAM than the AVR-based boards.  
I know that the NDEF library (which I imported) eats up a lot of RAM space.  When I find some time, I might look into that.

**Comment by LieBtrau** [comment]
This project uses a comparable chip with ATmega328.  It's well explained and described.  
[Elektor 140177 NFC Interface](https://www.elektormagazine.com/labs/140177-nfc-interface)
If I were you, I would start with this.  Get this working, which shouldn't be too hard and then start modifying it until it suits your needs.  You'll progress much faster than starting from scratch using some libs you find here and there on the internet.

**Comment by AA-IC-YPL** [comment]
Thanks, that's really helpful
