### ISSUE TITLE
How to connect the Arduino to the Ntag

### ISSUE THREAD

**Issue by TheBlune** [LieBtrau/arduino-ntag#17]
Hi there,

I consider myself lucky to have found your awesome library!
Unfortunately I am unable read from the code+schematics how exactly you connect the arduino to your PCB (which digital pin of the arduino is used to transmit the clock signal etc..). Can you help me? Did I miss something? 

Thanks in advance!

**Comment by LieBtrau** [comment]
Hi,
connections are quite simple:
CN1.1 = 3V3 of Arduino
CN1.2 = FD (=any IO-pin of the Arduino) -> pass it on to the ntag constructor
CN1.3 = SDA of the Arduino
CN1.4 = SCL of the Arduino
CN1.5 = VOUT (=any IO-pin of the Arduino)-> pass it on to the ntag constructor
CN1.6 = GND of the Arduino

As you can see for yourself in the example section, you need to pass the IO-numbers of the FD-pin and VOUT pin into the ntag-constructor.

**Comment by TheBlune** [comment]
Oops, I directly outed myself as an arduino newbee.. I completely ignored the pins with SCL and SDA printed onto the board. Thanks! 😄 

Okay, I tried your example of writing an NDEF to the Tag, but the arduino restarts itself on executing
ntagAdapter.write(message) 
(once i saw a quick "Write failed", but in all other cases the serial monitor just went wild from the restarting Arduino outputs)

I am using an arduino uno directly connected to an NTAG I2C Plus Antenna Board Rev 2.0 (Class 6 Antenna)

(Antenna Board) = (Arduino)
SCA = SCA
SDA = SDA 
VCC = 3V3 
GND = GND
FD = 2 (passed to the constructor like in your example WriteTag.ino)
VOUT = 5(passed to the constructor like in your example WriteTag.ino)

What could be the source of these restarts? 

The sketch already uses 32% space and the variables 28%...maybe your library is to much for my arduino?

**Comment by TheBlune** [comment]
Okay, I just noticed that the other issues https://github.com/LieBtrau/arduino-ntag/issues/10#issue-372749983 and  https://github.com/LieBtrau/arduino-ntag/issues/16#issue-467423249 seem to correlate here.. 

Maybe the solution for my needs is to just use a simplified version of your library that only writes NDEF messages blindly to the tag. How much of your library may I be able to cut by this?

**Comment by LieBtrau** [comment]
I tested the library on a STM32 Blue Pill, which has plenty of RAM.  I also had trouble on a Arduino with 8bit AVR MCU.  The NDEF-library (which I didn't write) eats up too much stack space.

If you're really a newbie, you could start with something that works and start modifying from that point onwards.  You'll progress quicker than starting from nothing.
Some tens of €'s will save you hours of struggling to get it working.  The choice is up to you.

Here are some links to get you started  : 
* [elektor](https://www.elektormagazine.com/labs/140177-nfc-interface)
* [mikroelektronika nfc tag](https://www.mikroe.com/nfc-tag-2-click) : requires a baseboard.  Their libraries are closed source.  I haven't tried it yet, but I think as a newbie you could easily start here.
* [OM23221ARD](https://www.digikey.be/product-detail/en/nxp-usa-inc/OM23221ARD/568-13441-ND/7431007).  It has an Arduino pinout, but NXP uses it with the MCUXpresso for FRDM-KW41Z.

**Comment by TheBlune** [comment]
Thanks for your advice and the links! Could you quickly add:
"Attention: The herein used NDEF-library (which I didn't write) currently eats up too much stack space for arduinos with 8bit AVR MCU and is therefore not usable." 
Or something similar to your readme? 

Good work btw..I will follow your advice! 

Cheers
