### ISSUE TITLE
Writing to NC_REG

### ISSUE THREAD

**Issue by IPMegladon** [LieBtrau/arduino-ntag#8]
Hi Christoph

Firstly we just want to make sure what the byte mask in writeRegister() in Ntag.cpp is and what its value should be.
And secondly we can't seem to be able to change any other Session register setting other than FD_OFF in NC_REG do you know why this could be and what we can do to fix it?

regards Megladon

**Comment by LieBtrau** [comment]
Hi Megladon,

To know how the writeRegister() function works, I suggest you to read the [NT3H1101 datasheet, §9.8 WRITE and READ register operation](http://www.nxp.com/docs/en/data-sheet/NT3H1101_1201.pdf).  It's all explained in detail.    

I don't know why it doesn't work for you.  In the ntag.cpp file, you can find numerous calls in the writeRegister function that write to other registers and bits (with success on my hardware).

Regards,
Christoph

**Comment by IPMegladon** [comment]
Thanks for the help, we already had the document but missed that small part describing the mask
